blank_issues_enabled: false
contact_links:
  - name: Security Vulnerability Reporting
    url: https://github.com/chikatina/casparser-js/security/advisories/new
    about: Report sensitive security vulnerabilities privately.
